#pragma once

typedef enum {
    ANCHOR_CENTER = 0,
    ANCHOR_TOP = 1,
    ANCHOR_BOTTOM = 2,
    ANCHOR_LEFT = 4,
    ANCHOR_RIGHT = 8,
    ANCHOR_TOP_LEFT = ANCHOR_TOP | ANCHOR_LEFT,
    ANCHOR_TOP_RIGHT = ANCHOR_TOP | ANCHOR_RIGHT,
    ANCHOR_BOTTOM_LEFT = ANCHOR_BOTTOM | ANCHOR_LEFT,
    ANCHOR_BOTTOM_RIGHT = ANCHOR_BOTTOM | ANCHOR_RIGHT,
} Anchor;
